### PR TITLE
Project Mode support for SA2 PC

### PR DESCRIPTION
**Pull request by calephelis**
Have added support for:
- Big the Cat
- Launch Panels
- Cages
- Chao Pipes
- Unbreakable Containers
- Dynamite Packs
- Master Emerald Shards
- Hint Monitors and SA1 Hint Monitors
- Item Balloons, and Item Boxes revealed via Mystic Melody or Sunglasses/Treasure Scope
- Level-Up Item Locations
- Small Animals (WIP)
- Mystic Melody Shrines, Platforms, and Doors
- Pulleys
- Groups of Rings, and Rings/Ring Groups revealed via Mystic Melody or Sunglasses/Treasure Scope
- Skulls
- Wide Springs, and Springs revealed via Mystic Melody or Sunglasses/Treasure Scope
- Switches

### CODE REVIEW

**Comment by PiKeyAr** [comment]
We should probably merge this before it becomes incompatible with the main branch...

**Review by Sora-yx — APPROVED** [review]
Looks good to me

**Comment by End-User-Person** [comment]
Sounds good.

**Comment by calephelis** [comment]
That's fine! I've been too busy with other things to work on this further.

**Pull request merged**
